name: Catalog Service
on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./secure-microservices\catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify


